theme: jekyll-theme-dinky

relative_links:
  enabled: true
  collections: true
include:
  - "Controlling the Robot.md"
  - "Directory.md"
  - "index.md"
  - "Map Assisted Localisation and Navigation.md"
  - "Matlab Refresher.md"
  - "The Task.md"